class CreateStaffs < ActiveRecord::Migration[7.2]
  def change
    create_table :staffs do |t|
      t.string :first_name
      t.string :last_name
      t.string :email
      t.string :password_digest
      t.string :role
      t.string :otp
      t.string :verify_otp
      t.datetime :otp_expires_at
      t.string :phone_number
      t.string :country_code
      t.string :alternative_number
      t.string :aadhaar_number
      t.string :pan_card
      t.date :date_of_birth
      t.string :gender
      t.string :business_name
      t.string :business_owner_type
      t.string :business_nature_type
      t.string :business_registration_number
      t.string :gst_number
      t.string :pan_number
      t.text :address
      t.string :city
      t.string :state
      t.string :pincode
      t.string :landmark
      t.string :username
      t.string :scheme
      t.string :referred_by
      t.string :bank_name
      t.string :account_number
      t.string :ifsc_code
      t.string :account_holder_name
      t.text :notes
      t.string :session_token
      t.integer :role_id
      t.boolean :status
      t.string :company_type
      t.string :company_name
      t.string :cin_number
      t.string :registration_certificate
      t.integer :user_admin_id
      t.string :confirm_password
      t.string :domain_name
      t.string :pan_card_image
      t.string :aadhaar_image
      t.string :passport_photo
      t.string :store_shop_photo
      t.string :address_proof_photo
      t.integer :parent_id
      t.string :set_pin
      t.string :confirm_pin
      t.float :latitude
      t.float :longitude
      t.datetime :captured_at
      t.datetime :last_seen_at
      t.string :ip_address
      t.string :location
      t.string :kyc_status
      t.string :kyc_method
      t.string :aadhaar_front_image
      t.string :aadhaar_back_image
      t.string :aadhaar_otp
      t.string :pan_otp
      t.string :pan_status
      t.string :aadhaar_status
      t.string :image
      t.boolean :kyc_verifications
      t.datetime :kyc_verified_at
      t.jsonb :kyc_data
      t.string :email_otp
      t.datetime :email_otp_sent_at
      t.string :set_mpin
      t.string :confirm_mpin
      t.boolean :status_mpin
      t.boolean :status_pin
      t.string :email_otp_status
      t.datetime :email_otp_verified_at
      t.boolean :set_pin_status
      t.string :user_code
      t.boolean :eko_onboard_first_step
      t.boolean :eko_profile_second_step
      t.string :eko_status_otp
      t.string :eko_verify_otp
      t.boolean :eko_biometric_kyc
      t.text :permanent_address
      t.string :permanent_landmark
      t.string :permanent_postal_code
      t.string :permanent_city
      t.string :permanent_state
      t.string :permanent_pincode

      t.timestamps
    end
  end
end
